export type ExamOption = "OK" | "Not OK" | "";

export interface ExamRow {
  id: string;
  label: string;            // Matches column name for status (e.g. "Ground Conditions:")
  commentsLabel: string;    // Matches column name for comments (e.g. "Comments GC:")
  mitigationLabel: string;  // Matches column name for mitigation (e.g. "Mitigation GC:")
  value: ExamOption;
  comments: string;
  mitigation: string;
}

export const INITIAL_EXAM_ROWS: ExamRow[] = [
  {
    id: "ground_conditions",
    label: "Ground Conditions:",
    commentsLabel: "Comments GC:",
    mitigationLabel: "Mitigation GC:",
    value: "",
    comments: "",
    mitigation: "",
  },
  {
    id: "steps_ladders",
    label: "Steps & Ladders:",
    commentsLabel: "Comments SL:",
    mitigationLabel: "Mitigation SL:",
    value: "",
    comments: "",
    mitigation: "",
  },
  {
    id: "walkways",
    label: "Walkways:",
    commentsLabel: "Comments W:",
    mitigationLabel: "Mitigation W:",
    value: "",
    comments: "",
    mitigation: "",
  },
  {
    id: "handrails_toeboards",
    label: "Handrails & Toeboards:",
    commentsLabel: "Comments HT:",
    mitigationLabel: "Mitigation HT:",
    value: "",
    comments: "",
    mitigation: "",
  },
  {
    id: "guarding",
    label: "Guarding:",
    commentsLabel: "Comments G:",
    mitigationLabel: "Mitigation G:",
    value: "",
    comments: "",
    mitigation: "",
  },
  {
    id: "structural_damage",
    label: "Structural Damage:",
    commentsLabel: "Comments SD:",
    mitigationLabel: "Mitigation SD:",
    value: "",
    comments: "",
    mitigation: "",
  },
  {
    id: "electrical",
    label: "Electrical:",
    commentsLabel: "Comments E:",
    mitigationLabel: "Mitigation E:",
    value: "",
    comments: "",
    mitigation: "",
  },
  {
    id: "belt_conveyors",
    label: "Belt Conveyors:",
    commentsLabel: "Comments BC:",
    mitigationLabel: "Mitigation BC:",
    value: "",
    comments: "",
    mitigation: "",
  },
  {
    id: "emergency_stops",
    label: "Emergency Stops:",
    commentsLabel: "Comments ES:",
    mitigationLabel: "Mitigation ES:",
    value: "",
    comments: "",
    mitigation: "",
  },
  {
    id: "motors_drives",
    label: "Motors & Drives:",
    commentsLabel: "Comments MD:",
    mitigationLabel: "Mitigation MD:",
    value: "",
    comments: "",
    mitigation: "",
  },
  {
    id: "material_build_up",
    label: "Material Build Up:",
    commentsLabel: "Comments MB:",
    mitigationLabel: "Mitigation MB:",
    value: "",
    comments: "",
    mitigation: "",
  },
  {
    id: "screws",
    label: "Screws:",
    commentsLabel: "Comments S:",
    mitigationLabel: "Mitigation S:",
    value: "",
    comments: "",
    mitigation: "",
  },
  {
    id: "screens",
    label: "Screens:",
    commentsLabel: "Comments SC:",
    mitigationLabel: "Mitigation SC:",
    value: "",
    comments: "",
    mitigation: "",
  },
  {
    id: "fire_extinguishers",
    label: "Fire Extinguishers:",
    commentsLabel: "Comments FE:",
    mitigationLabel: "Mitigation FE:",
    value: "",
    comments: "",
    mitigation: "",
  },
  {
    id: "start_up_alarms",
    label: "Start Up Alarms:",
    commentsLabel: "Comments SA:",
    mitigationLabel: "Mitigation SA:",
    value: "",
    comments: "",
    mitigation: "",
  },
  {
    id: "signage",
    label: "Signage:",
    commentsLabel: "Comments SG:",
    mitigationLabel: "Mitigation SG:",
    value: "",
    comments: "",
    mitigation: "",
  },
  {
    id: "mcc_room",
    label: "MCC Room:",
    commentsLabel: "Comments MCC:",
    mitigationLabel: "Mitigation MCC:",
    value: "",
    comments: "",
    mitigation: "",
  },
  {
    id: "housekeeping",
    label: "Housekeeping:",
    commentsLabel: "Comments H:",
    mitigationLabel: "Mitigation H:",
    value: "",
    comments: "",
    mitigation: "",
  },
];

export const OPTION_COLORS = {
  "OK": "bg-green-600 border-green-600 text-white",
  "Not OK": "bg-red-600 border-red-600 text-white",
};
